AWSTemplateFormatVersion: '2010-09-09'
Resources:

  # Security Group Creation with VPC ID specified
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Allow all inbound and outbound traffic"
      VpcId: 'vpc-04ee0c054fd5204f8'  # Specify the VPC ID
      # Inbound rules (allow all traffic on all ports)
      SecurityGroupIngress:
        - IpProtocol: "-1"  # -1 means all protocols (all ports)
          CidrIp: "0.0.0.0/0"  # Allows all inbound traffic from anywhere
          
      # Outbound rules (allow all outbound traffic to anywhere)
      SecurityGroupEgress:
        - IpProtocol: "-1"  # -1 means all protocols (all ports)
          CidrIp: "0.0.0.0/0"  # Allows all outbound traffic to anywhere

  # EC2 Instance Creation
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro  # Instance type is fixed to t2.micro
      ImageId: 'ami-0ea3c35c5c3284d82'  # Your AMI ID
      SecurityGroupIds:
        - !Ref MySecurityGroup  # Reference the newly created security group
      Tags:
        - Key: Name
          Value: MyEC2Instance

Outputs:
  InstanceId:
    Description: "The Instance ID"
    Value: !Ref MyEC2Instance

  PublicIP:
    Description: "The public IP address of the EC2 instance"
    Value: !GetAtt MyEC2Instance.PublicIp

  SecurityGroupId:
    Description: "The ID of the Security Group"
    Value: !Ref MySecurityGroup
AWSTemplateFormatVersion: '2010-09-09'
Resources:

  # Security Group Creation with VPC ID specified
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: "Allow all inbound and outbound traffic"
      VpcId: 'vpc-0123456789abcdef0'  # Random placeholder VPC ID
      # Inbound rules (allow all traffic on all ports)
      SecurityGroupIngress:
        - IpProtocol: "-1"  # -1 means all protocols (all ports)
          CidrIp: "0.0.0.0/0"  # Allows all inbound traffic from anywhere
          
      # Outbound rules (allow all outbound traffic to anywhere)
      SecurityGroupEgress:
        - IpProtocol: "-1"  # -1 means all protocols (all ports)
          CidrIp: "0.0.0.0/0"  # Allows all outbound traffic to anywhere

  # EC2 Instance Creation
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro  # Instance type is fixed to t2.micro
      ImageId: 'ami-1234567890abcdef0'  # Random placeholder AMI ID
      SecurityGroupIds:
        - !Ref MySecurityGroup  # Reference the newly created security group
      Tags:
        - Key: Name
          Value: MyEC2Instance

Outputs:
  InstanceId:
    Description: "The Instance ID"
    Value: !Ref MyEC2Instance

  PublicIP:
    Description: "The public IP address of the EC2 instance"
    Value: !GetAtt MyEC2Instance.PublicIp

  SecurityGroupId:
    Description: "The ID of the Security Group"
    Value: !Ref MySecurityGroup
